//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vcall_Customer
    {
        public long Id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Guid { get; set; }
        public Nullable<int> Customer_Hits { get; set; }
        public string Customer_FailPhone { get; set; }
        public string Customer_logo { get; set; }
        public Nullable<int> Customer_MaxQuestion { get; set; }
    }
}
