//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vcall_Questions
    {
        public int Id { get; set; }
        public string Question_text { get; set; }
        public Nullable<long> Question_Active { get; set; }
        public string Question_text_V1 { get; set; }
        public string Question_text_V2 { get; set; }
        public string Question_text_V3 { get; set; }
        public string Question_Type { get; set; }
        public Nullable<long> Question_Cust_Id_Fk { get; set; }
        public Nullable<int> Question_Sort { get; set; }
    }
}
